import { AgentDefinition } from "../types/agent";

export const CORE_AGENT_ROSTER: AgentDefinition[] = [
  {
    id: "agent-conductor",
    name: "ULTRON Conductor",
    role: "CONDUCTOR",
    domain: "Orchestration & Cognitive Kernel",
    description: "Chief supervisor responsible for intent parsing, DAG compilation, specialist delegation, and verification gating.",
    avatarColor: "#ffaa30",
    riskLevel: "MEDIUM",
    capabilities: ["dag_planning", "task_delegation", "conflict_resolution", "verification_orchestration"],
    requiredSkills: ["orchestration", "system_planning"],
    allowedTools: ["system_telemetry", "filesystem_inspector"],
    prohibitedTools: ["sandbox_terminal"],
    systemPrompt: "You are the ULTRON Conductor. Lead the agent fleet, maintain structural rigor, decompose missions into DAGs, and ensure zero unverified completions.",
    status: "THINKING",
    metrics: {
      totalTasksCompleted: 142,
      totalTokensUsed: 420000,
      totalCostUsd: 1.25,
      successRate: 0.98,
      avgDurationSec: 4.2,
      verificationPassRate: 0.99,
    },
  },
  {
    id: "agent-researcher",
    name: "Deep Researcher",
    role: "RESEARCHER",
    domain: "Information Retrieval & Grounding",
    description: "Autonomous multi-source evidence gatherer. Formulates search vectors, scores domain authority, and tracks citations.",
    avatarColor: "#00f0ff",
    riskLevel: "LOW",
    capabilities: ["multi_source_search", "atomic_claim_extraction", "citation_graph"],
    requiredSkills: ["search_expansion", "evidence_extraction"],
    allowedTools: ["browser_search", "filesystem_inspector"],
    prohibitedTools: ["sandbox_terminal"],
    systemPrompt: "You are the ULTRON Researcher. Seek ground truth, challenge unverified assumptions, and always cite primary URLs.",
    status: "IDLE",
    metrics: {
      totalTasksCompleted: 310,
      totalTokensUsed: 890000,
      totalCostUsd: 2.15,
      successRate: 0.96,
      avgDurationSec: 8.5,
      verificationPassRate: 0.94,
    },
  },
  {
    id: "agent-architect",
    name: "System Architect",
    role: "ARCHITECT",
    domain: "System Topology & Technical Invariants",
    description: "Designs schemas, API contracts, domain boundaries, and data flow topologies.",
    avatarColor: "#a855f7",
    riskLevel: "LOW",
    capabilities: ["schema_design", "api_contracts", "monorepo_organization"],
    requiredSkills: ["system_architecture", "typescript_patterns"],
    allowedTools: ["filesystem_inspector"],
    prohibitedTools: ["sandbox_terminal"],
    systemPrompt: "You are the ULTRON System Architect. Maintain separation of concerns, enforce type safety, and eliminate architectural rot.",
    status: "IDLE",
    metrics: {
      totalTasksCompleted: 88,
      totalTokensUsed: 310000,
      totalCostUsd: 0.92,
      successRate: 1.0,
      avgDurationSec: 5.1,
      verificationPassRate: 1.0,
    },
  },
  {
    id: "agent-builder",
    name: "Full-Stack Builder",
    role: "BUILDER",
    domain: "Implementation & Code Synthesis",
    description: "Synthesizes robust, production-grade frontend components, backend services, and unit test suites.",
    avatarColor: "#22c55e",
    riskLevel: "HIGH",
    capabilities: ["code_synthesis", "refactoring", "unit_test_authoring"],
    requiredSkills: ["nextjs", "react", "fastapi", "typescript"],
    allowedTools: ["filesystem_inspector", "sandbox_terminal"],
    prohibitedTools: [],
    systemPrompt: "You are the ULTRON Builder. Write elegant, clean code without placeholder mocks. Write tests for every critical execution path.",
    status: "EXECUTING",
    metrics: {
      totalTasksCompleted: 245,
      totalTokensUsed: 1250000,
      totalCostUsd: 4.8,
      successRate: 0.94,
      avgDurationSec: 12.4,
      verificationPassRate: 0.92,
    },
  },
  {
    id: "agent-security",
    name: "Defensive Security Sentinel",
    role: "SECURITY",
    domain: "Zero-Trust Hardening & SAST Audit",
    description: "Monitors tool invocations, audits AST for secret leakage, enforces least-privilege policies, and manages approval gates.",
    avatarColor: "#ef4444",
    riskLevel: "MEDIUM",
    capabilities: ["sast_audit", "cve_triage", "secret_redaction", "policy_enforcement"],
    requiredSkills: ["defensive_security", "owasp_hardening"],
    allowedTools: ["security_scanner", "filesystem_inspector"],
    prohibitedTools: ["sandbox_terminal"],
    systemPrompt: "You are the ULTRON Security Sentinel. Enforce strict defensive posture. Prevent unauthorized network egress, secret leaks, and unapproved changes.",
    status: "IDLE",
    metrics: {
      totalTasksCompleted: 178,
      totalTokensUsed: 460000,
      totalCostUsd: 1.1,
      successRate: 0.99,
      avgDurationSec: 3.2,
      verificationPassRate: 1.0,
    },
  },
  {
    id: "agent-reality-checker",
    name: "Reality Checker",
    role: "REALITY_CHECKER",
    domain: "Empirical Verification & Assertion Gate",
    description: "ULTRON's failsafe against hallucinated success. Verifies that deliverables satisfy original objectives, tests pass, and facts hold.",
    avatarColor: "#eab308",
    riskLevel: "LOW",
    capabilities: ["empirical_testing", "citation_audit", "objective_distance_scoring"],
    requiredSkills: ["reality_verification", "assertion_testing"],
    allowedTools: ["filesystem_inspector", "system_telemetry"],
    prohibitedTools: [],
    systemPrompt: "You are the ULTRON Reality Checker. Never accept unverified claims. Check exit codes, verify URLs, measure semantic drift.",
    status: "IDLE",
    metrics: {
      totalTasksCompleted: 195,
      totalTokensUsed: 520000,
      totalCostUsd: 1.35,
      successRate: 0.97,
      avgDurationSec: 4.8,
      verificationPassRate: 0.96,
    },
  },
  {
    id: "agent-memory-curator",
    name: "Memory Curator",
    role: "MEMORY_CURATOR",
    domain: "Knowledge & Durable Memory Governance",
    description: "Governs L0-L4 memory tiers. Deduplicates claims, detects contradictions, calculates confidence scores, and archives stale data.",
    avatarColor: "#3b82f6",
    riskLevel: "LOW",
    capabilities: ["memory_deduplication", "conflict_resolution", "l4_promotion"],
    requiredSkills: ["knowledge_governance", "pgvector_indexing"],
    allowedTools: ["filesystem_inspector"],
    prohibitedTools: ["sandbox_terminal"],
    systemPrompt: "You are the ULTRON Memory Curator. Maintain the purity of long-term memory. Only verified facts with proof may enter L4.",
    status: "IDLE",
    metrics: {
      totalTasksCompleted: 112,
      totalTokensUsed: 280000,
      totalCostUsd: 0.72,
      successRate: 0.99,
      avgDurationSec: 3.0,
      verificationPassRate: 1.0,
    },
  },
];
