import { AgentDefinition } from "../types/agent";

export const CORE_AGENT_ROSTER: AgentDefinition[] = [
  {
    id: "agent-conductor",
    name: "ULTRON Conductor",
    role: "CONDUCTOR",
    domain: "Orchestration & Cognitive Kernel",
    description: "Chief supervisor responsible for intent parsing, DAG compilation, specialist delegation, and verification gating.",
    avatarColor: "#ffaa30",
    riskLevel: "MEDIUM",
    status: "READY",
    currentTask: "Supervising cognitive loop & event bus",
    lastActivity: "Synchronized active mission topology",
    capabilities: ["dag_planning", "task_delegation", "conflict_resolution", "verification_orchestration"],
    tools: ["system_telemetry", "filesystem_inspector", "mission_scheduler"],
    permissions: ["orchestration:read", "orchestration:write", "missions:manage"],
    requiredSkills: ["orchestration", "system_planning"],
    allowedTools: ["system_telemetry", "filesystem_inspector"],
    prohibitedTools: ["sandbox_terminal"],
    systemPrompt: "You are the ULTRON Conductor. Lead the agent fleet, maintain structural rigor, decompose missions into DAGs, and ensure zero unverified completions.",
    metrics: {
      totalTasksCompleted: 142,
      totalTokensUsed: 420000,
      totalCostUsd: 1.25,
      successRate: 0.98,
      avgDurationSec: 4.2,
      verificationPassRate: 0.99,
    },
  },
  {
    id: "agent-researcher",
    name: "Deep Researcher",
    role: "RESEARCHER",
    domain: "Information Retrieval & Grounding",
    description: "Autonomous multi-source evidence gatherer. Formulates search vectors, scores domain authority, and tracks citations.",
    avatarColor: "#00f0ff",
    riskLevel: "LOW",
    status: "IDLE",
    currentTask: "Standing by for query retrieval",
    lastActivity: "Indexed Google Gemini Live documentation",
    capabilities: ["multi_source_search", "atomic_claim_extraction", "citation_graph"],
    tools: ["browser_search", "filesystem_inspector", "web_fetch"],
    permissions: ["web:search", "filesystem:read"],
    requiredSkills: ["search_expansion", "evidence_extraction"],
    allowedTools: ["browser_search", "filesystem_inspector"],
    prohibitedTools: ["sandbox_terminal"],
    systemPrompt: "You are the ULTRON Researcher. Seek ground truth, challenge unverified assumptions, and always cite primary URLs.",
    metrics: {
      totalTasksCompleted: 310,
      totalTokensUsed: 890000,
      totalCostUsd: 2.15,
      successRate: 0.96,
      avgDurationSec: 8.5,
      verificationPassRate: 0.94,
    },
  },
  {
    id: "agent-builder",
    name: "Full-Stack Builder",
    role: "BUILDER",
    domain: "Implementation & Code Synthesis",
    description: "Synthesizes robust, production-grade frontend components, backend services, and unit test suites.",
    avatarColor: "#22c55e",
    riskLevel: "HIGH",
    status: "READY",
    currentTask: "Synthesizing voice command bar & Gemini Live bridge",
    lastActivity: "Compiled persistent UltronShell layout",
    capabilities: ["code_synthesis", "refactoring", "unit_test_authoring"],
    tools: ["filesystem_inspector", "code_compiler", "sandbox_terminal"],
    permissions: ["code:read", "code:write", "terminal:execute_with_approval"],
    requiredSkills: ["nextjs", "react", "fastapi", "typescript"],
    allowedTools: ["filesystem_inspector", "sandbox_terminal"],
    prohibitedTools: [],
    systemPrompt: "You are the ULTRON Builder. Write elegant, clean code without placeholder mocks. Write tests for every critical execution path.",
    metrics: {
      totalTasksCompleted: 245,
      totalTokensUsed: 1250000,
      totalCostUsd: 4.8,
      successRate: 0.94,
      avgDurationSec: 12.4,
      verificationPassRate: 0.92,
    },
  },
  {
    id: "agent-designer",
    name: "Design & UX Architect",
    role: "DESIGNER",
    domain: "Interface Aesthetics & Ergonomics",
    description: "Governs design tokens, micro-interactions, responsive command decks, typography hierarchy, and visual telemetry.",
    avatarColor: "#c084fc",
    riskLevel: "LOW",
    status: "READY",
    currentTask: "Enforcing unified ULTRON color tokens & contrast",
    lastActivity: "Validated zero-black-text contract across 7 modules",
    capabilities: ["design_system_governance", "contrast_validation", "responsive_layout_audit"],
    tools: ["css_token_inspector", "viewport_simulator"],
    permissions: ["styles:read", "styles:write"],
    requiredSkills: ["vanilla_css", "design_systems", "micro_interactions"],
    allowedTools: ["filesystem_inspector"],
    prohibitedTools: ["sandbox_terminal"],
    systemPrompt: "You are the ULTRON Designer. Maintain visual excellence, flawless dark mode ergonomics, and premium technical aesthetics.",
    metrics: {
      totalTasksCompleted: 98,
      totalTokensUsed: 290000,
      totalCostUsd: 0.85,
      successRate: 0.99,
      avgDurationSec: 3.8,
      verificationPassRate: 1.0,
    },
  },
  {
    id: "agent-security",
    name: "Defensive Security Sentinel",
    role: "SECURITY",
    domain: "Zero-Trust Hardening & SAST Audit",
    description: "Monitors tool invocations, audits AST for secret leakage, enforces least-privilege policies, and manages approval gates.",
    avatarColor: "#ef4444",
    riskLevel: "MEDIUM",
    status: "READY",
    currentTask: "Guarding API key boundaries and approval queue",
    lastActivity: "Verified GEMINI_API_KEY server-side confinement",
    capabilities: ["sast_audit", "cve_triage", "secret_redaction", "policy_enforcement"],
    tools: ["security_scanner", "filesystem_inspector", "secret_scrubber"],
    permissions: ["security:audit", "approvals:gate", "policy:enforce"],
    requiredSkills: ["defensive_security", "owasp_hardening"],
    allowedTools: ["security_scanner", "filesystem_inspector"],
    prohibitedTools: ["sandbox_terminal"],
    systemPrompt: "You are the ULTRON Security Sentinel. Enforce strict defensive posture. Prevent unauthorized network egress, secret leaks, and unapproved changes.",
    metrics: {
      totalTasksCompleted: 178,
      totalTokensUsed: 460000,
      totalCostUsd: 1.1,
      successRate: 0.99,
      avgDurationSec: 3.2,
      verificationPassRate: 1.0,
    },
  },
  {
    id: "agent-qa",
    name: "Quality Assurance Engineer",
    role: "QA",
    domain: "Automated Testing & Regression Suites",
    description: "Executes end-to-end integration tests, verifies route responses, validates status transitions, and detects regressions.",
    avatarColor: "#14b8a6",
    riskLevel: "LOW",
    status: "READY",
    currentTask: "Verifying HTML contract and route availability",
    lastActivity: "Executed route verification across /core to /system",
    capabilities: ["e2e_test_execution", "regression_testing", "contract_validation"],
    tools: ["test_runner", "http_client", "dom_inspector"],
    permissions: ["test:execute", "metrics:read"],
    requiredSkills: ["jest", "playwright", "integration_testing"],
    allowedTools: ["filesystem_inspector", "system_telemetry"],
    prohibitedTools: ["sandbox_terminal"],
    systemPrompt: "You are the ULTRON QA Engineer. Ensure every route renders cleanly, every button executes real actions, and zero regressions pass.",
    metrics: {
      totalTasksCompleted: 165,
      totalTokensUsed: 390000,
      totalCostUsd: 0.95,
      successRate: 0.97,
      avgDurationSec: 4.1,
      verificationPassRate: 0.98,
    },
  },
  {
    id: "agent-reality-checker",
    name: "Reality Checker",
    role: "REALITY_CHECKER",
    domain: "Empirical Verification & Assertion Gate",
    description: "ULTRON's failsafe against hallucinated success. Verifies that deliverables satisfy original objectives, tests pass, and facts hold.",
    avatarColor: "#eab308",
    riskLevel: "LOW",
    status: "READY",
    currentTask: "Awaiting task verification assertions",
    lastActivity: "Validated mission deliverables against user intent",
    capabilities: ["empirical_testing", "citation_audit", "objective_distance_scoring"],
    tools: ["filesystem_inspector", "system_telemetry", "assertion_engine"],
    permissions: ["verification:audit", "missions:assert"],
    requiredSkills: ["reality_verification", "assertion_testing"],
    allowedTools: ["filesystem_inspector", "system_telemetry"],
    prohibitedTools: [],
    systemPrompt: "You are the ULTRON Reality Checker. Never accept unverified claims. Check exit codes, verify URLs, measure semantic drift.",
    metrics: {
      totalTasksCompleted: 195,
      totalTokensUsed: 520000,
      totalCostUsd: 1.35,
      successRate: 0.97,
      avgDurationSec: 4.8,
      verificationPassRate: 0.96,
    },
  },
  {
    id: "agent-memory-curator",
    name: "Memory Curator",
    role: "MEMORY_CURATOR",
    domain: "Knowledge & Durable Memory Governance",
    description: "Governs L0-L4 memory tiers. Deduplicates claims, detects contradictions, calculates confidence scores, and archives stale data.",
    avatarColor: "#3b82f6",
    riskLevel: "LOW",
    status: "READY",
    currentTask: "Maintaining L0-L4 promotion gates & vector index",
    lastActivity: "Indexed project invariants into L4 store",
    capabilities: ["memory_deduplication", "conflict_resolution", "l4_promotion"],
    tools: ["memory_store", "vector_indexer", "claim_validator"],
    permissions: ["memory:read", "memory:write", "memory:promote"],
    requiredSkills: ["knowledge_governance", "pgvector_indexing"],
    allowedTools: ["filesystem_inspector"],
    prohibitedTools: ["sandbox_terminal"],
    systemPrompt: "You are the ULTRON Memory Curator. Maintain the purity of long-term memory. Only verified facts with proof may enter L4.",
    metrics: {
      totalTasksCompleted: 112,
      totalTokensUsed: 280000,
      totalCostUsd: 0.72,
      successRate: 0.99,
      avgDurationSec: 3.0,
      verificationPassRate: 1.0,
    },
  },
  {
    id: "agent-devops",
    name: "DevOps & Infrastructure Engineer",
    role: "DEVOPS",
    domain: "Build Pipeline & Deployment Control",
    description: "Monitors build health, memory consumption, daemon processes, environment parity, and Vercel/Node deployment pipelines.",
    avatarColor: "#06b6d4",
    riskLevel: "MEDIUM",
    status: "READY",
    currentTask: "Monitoring Next.js production build & server daemon",
    lastActivity: "Verified port 3000 daemon health and memory limits",
    capabilities: ["build_monitoring", "process_management", "deployment_automation"],
    tools: ["process_monitor", "build_inspector", "env_auditor"],
    permissions: ["system:metrics", "build:trigger"],
    requiredSkills: ["nextjs_build", "docker", "vercel_deploy"],
    allowedTools: ["system_telemetry", "filesystem_inspector"],
    prohibitedTools: [],
    systemPrompt: "You are the ULTRON DevOps Engineer. Keep build green, optimize memory, enforce server invariants, and safeguard deployments.",
    metrics: {
      totalTasksCompleted: 78,
      totalTokensUsed: 210000,
      totalCostUsd: 0.54,
      successRate: 0.98,
      avgDurationSec: 6.2,
      verificationPassRate: 0.99,
    },
  },
  {
    id: "agent-analyst",
    name: "System & World Intelligence Analyst",
    role: "ANALYST",
    domain: "Telemetry Telemetry & External Intelligence Synthesis",
    description: "Correlates external intelligence streams with local telemetry, tracks model latency, and scores freshness and provenance.",
    avatarColor: "#f43f5e",
    riskLevel: "LOW",
    status: "IDLE",
    currentTask: "Evaluating external intelligence feeds",
    lastActivity: "Assessed provenance scores for world feeds",
    capabilities: ["telemetry_analysis", "provenance_scoring", "anomaly_detection"],
    tools: ["world_feed_monitor", "telemetry_analyzer", "metrics_grapher"],
    permissions: ["world:read", "metrics:read"],
    requiredSkills: ["data_analysis", "time_series", "provenance_modeling"],
    allowedTools: ["system_telemetry", "browser_search"],
    prohibitedTools: ["sandbox_terminal"],
    systemPrompt: "You are the ULTRON Analyst. Distinguish live signal from inferred projection. Enforce provenance tags and freshness timestamps.",
    metrics: {
      totalTasksCompleted: 84,
      totalTokensUsed: 230000,
      totalCostUsd: 0.61,
      successRate: 0.99,
      avgDurationSec: 3.5,
      verificationPassRate: 0.99,
    },
  },
];
