import { FreeToolDefinition } from "../types/tool";

export const FREE_TOOLS_CATALOG: FreeToolDefinition[] = [
  // A. Image & Design Tools
  {
    id: "squoosh",
    name: "Squoosh Image Optimizer",
    description: "Browser & local image compression and format transcoding (WebP/JPEG/PNG) with exact byte measurements and artifact generation.",
    category: "Image & Design",
    websiteUrl: "https://squoosh.app/",
    documentationUrl: "https://github.com/GoogleChromeLabs/squoosh",
    executionMode: "local",
    pricingStatus: "free_core",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "approved",
    inputSchema: {
      type: "object",
      properties: {
        format: { type: "string", enum: ["webp", "jpeg", "png"], default: "webp" },
        quality: { type: "number", minimum: 1, maximum: 100, default: 75 },
        maxWidth: { type: "number", default: 1920 },
      },
      required: ["format"],
    },
    outputSchema: {
      type: "object",
      properties: {
        originalSizeBytes: { type: "number" },
        compressedSizeBytes: { type: "number" },
        savingsPercent: { type: "number" },
        artifactUrl: { type: "string" },
      },
    },
    requiredPermissions: ["filesystem:write_artifact"],
    supportedPlatforms: ["Browser", "Node.js", "Desktop"],
    availabilityStatus: "AVAILABLE",
    limitations: [
      "Client-side canvas or local Node buffer processing",
      "Maximum recommended single input payload: 15MB",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://squoosh.app/",
    healthStatus: "OPERATIONAL",
    riskLevel: "L1",
    actionType: "LOCAL_IMAGE_COMPRESS",
  },
  {
    id: "photopea",
    name: "Photopea Advanced Image Editor",
    description: "Full-featured Photoshop/PSD web editor running client-side. Open workspace, complete graphic edits, and return exported assets to ULTRON.",
    category: "Image & Design",
    websiteUrl: "https://www.photopea.com/",
    documentationUrl: "https://www.photopea.com/api/",
    executionMode: "user_opened_website",
    pricingStatus: "free_core",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "user_interaction_required",
    inputSchema: {
      type: "object",
      properties: {
        documentUrl: { type: "string", description: "Optional image or PSD URL to load" },
      },
    },
    outputSchema: {
      type: "object",
      properties: {
        exportedAssetPath: { type: "string" },
      },
    },
    requiredPermissions: ["browser:open_window"],
    supportedPlatforms: ["Browser"],
    availabilityStatus: "AVAILABLE",
    limitations: [
      "Ad-supported free tier with complete PSD/vector tooling",
      "Requires human editing interaction; no headless batch API without premium key",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://www.photopea.com/privacy",
    healthStatus: "OPERATIONAL",
    riskLevel: "L0",
    actionType: "LAUNCH_EXTERNAL",
  },
  {
    id: "remove_bg",
    name: "remove.bg Background Remover",
    description: "Automated portrait and product subject isolation and background removal tool.",
    category: "Image & Design",
    websiteUrl: "https://www.remove.bg/",
    documentationUrl: "https://www.remove.bg/api",
    executionMode: "user_opened_website",
    pricingStatus: "freemium",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "user_interaction_required",
    inputSchema: {
      type: "object",
      properties: {
        imageUrl: { type: "string" },
      },
    },
    outputSchema: {
      type: "object",
      properties: {
        resultUrl: { type: "string" },
      },
    },
    requiredPermissions: ["browser:open_window"],
    supportedPlatforms: ["Browser", "API (paid)"],
    availabilityStatus: "RESTRICTED",
    limitations: [
      "Web interface grants 1 free low-resolution preview without subscription",
      "Full HD export and batch API automation require paid monthly credits",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://www.remove.bg/terms",
    healthStatus: "OPERATIONAL",
    riskLevel: "L0",
    actionType: "LAUNCH_EXTERNAL",
  },
  {
    id: "cleanup_pictures",
    name: "Cleanup.pictures Inpainting",
    description: "AI inpainting tool for removing unwanted objects, text, defects, or people from photographs.",
    category: "Image & Design",
    websiteUrl: "https://cleanup.pictures/",
    documentationUrl: "https://cleanup.pictures/",
    executionMode: "user_opened_website",
    pricingStatus: "freemium",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "user_interaction_required",
    inputSchema: {
      type: "object",
      properties: {
        imageUrl: { type: "string" },
      },
    },
    outputSchema: {
      type: "object",
      properties: {
        cleanedImageUrl: { type: "string" },
      },
    },
    requiredPermissions: ["browser:open_window"],
    supportedPlatforms: ["Browser"],
    availabilityStatus: "AVAILABLE",
    limitations: [
      "Free version limited to standard 720p output resolution",
      "High-resolution HD output requires Pro subscription",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://cleanup.pictures/terms",
    healthStatus: "OPERATIONAL",
    riskLevel: "L0",
    actionType: "LAUNCH_EXTERNAL",
  },
  {
    id: "unscreen",
    name: "Unscreen Video Background Removal",
    description: "Automated video background eraser for MP4/GIF clips (redirected into Canva Video suite).",
    category: "Image & Design",
    websiteUrl: "https://www.unscreen.com/",
    documentationUrl: "https://www.unscreen.com/api",
    executionMode: "user_opened_website",
    pricingStatus: "freemium",
    subscriptionRequiredForIntendedUse: true,
    automationPermission: "user_interaction_required",
    inputSchema: {
      type: "object",
      properties: {
        videoUrl: { type: "string" },
      },
    },
    outputSchema: {
      type: "object",
      properties: {
        cutoutVideoUrl: { type: "string" },
      },
    },
    requiredPermissions: ["browser:open_window"],
    supportedPlatforms: ["Browser"],
    availabilityStatus: "RESTRICTED",
    limitations: [
      "Acquired and redirected to Canva Video background removal ecosystem",
      "Free tier limited to 5-second low-resolution preview clips with watermark",
      "Full video processing requires Canva Pro subscription",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://www.canva.com/policies/terms-of-use/",
    healthStatus: "DEGRADED",
    riskLevel: "L0",
    actionType: "LAUNCH_EXTERNAL",
  },

  // B. Developer & Visual Communication Tools
  {
    id: "carbon",
    name: "Carbon Code Screenshots",
    description: "Create beautiful source code screenshots and presentation cards with pre-filled syntax.",
    category: "Developer Tools",
    websiteUrl: "https://carbon.now.sh/",
    documentationUrl: "https://github.com/carbon-app/carbon",
    executionMode: "user_opened_website",
    pricingStatus: "free_core",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "user_interaction_required",
    inputSchema: {
      type: "object",
      properties: {
        code: { type: "string", description: "Source code to render" },
        language: { type: "string", default: "typescript" },
        theme: { type: "string", default: "one-dark" },
      },
      required: ["code"],
    },
    outputSchema: {
      type: "object",
      properties: {
        launchUrl: { type: "string" },
      },
    },
    requiredPermissions: ["browser:open_window"],
    supportedPlatforms: ["Browser"],
    availabilityStatus: "AVAILABLE",
    limitations: [
      "URL query string prefill (?code=...); browser downloads rendered PNG directly",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://carbon.now.sh/about",
    healthStatus: "OPERATIONAL",
    riskLevel: "L0",
    actionType: "LAUNCH_EXTERNAL",
  },
  {
    id: "ray_so",
    name: "Ray.so Code Cards",
    description: "Generate elegant code snippet cards with customizable gradients, dark themes, and paddings.",
    category: "Developer Tools",
    websiteUrl: "https://ray.so/",
    documentationUrl: "https://github.com/raycast/ray-so",
    executionMode: "user_opened_website",
    pricingStatus: "free_core",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "user_interaction_required",
    inputSchema: {
      type: "object",
      properties: {
        code: { type: "string" },
        title: { type: "string", default: "snippet" },
        theme: { type: "string", default: "breeze" },
      },
      required: ["code"],
    },
    outputSchema: {
      type: "object",
      properties: {
        launchUrl: { type: "string" },
      },
    },
    requiredPermissions: ["browser:open_window"],
    supportedPlatforms: ["Browser"],
    availabilityStatus: "AVAILABLE",
    limitations: [
      "Code is prefilled via base64 URL fragment; export is performed by user in browser",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://raycast.com/terms",
    healthStatus: "OPERATIONAL",
    riskLevel: "L0",
    actionType: "LAUNCH_EXTERNAL",
  },
  {
    id: "shots_so",
    name: "Shots Mockup Studio",
    description: "Generate browser, mobile device, and laptop framed presentation mockups for screenshots.",
    category: "Developer Tools",
    websiteUrl: "https://shots.so/",
    documentationUrl: "https://shots.so/",
    executionMode: "user_opened_website",
    pricingStatus: "freemium",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "user_interaction_required",
    inputSchema: {
      type: "object",
      properties: {
        frameType: { type: "string", enum: ["browser", "iphone", "macbook"] },
      },
    },
    outputSchema: {
      type: "object",
      properties: {
        mockupUrl: { type: "string" },
      },
    },
    requiredPermissions: ["browser:open_window"],
    supportedPlatforms: ["Browser"],
    availabilityStatus: "AVAILABLE",
    limitations: [
      "Free core frames and backgrounds available without watermark",
      "Pro frames and 4K vector exports require Shots Pro",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://shots.so/terms",
    healthStatus: "OPERATIONAL",
    riskLevel: "L0",
    actionType: "LAUNCH_EXTERNAL",
  },
  {
    id: "smartmockups",
    name: "Smartmockups Product Mockups",
    description: "Photorealistic digital and print device mockup generator (integrated into Canva Mockups).",
    category: "Developer Tools",
    websiteUrl: "https://smartmockups.com/",
    documentationUrl: "https://smartmockups.com/",
    executionMode: "user_opened_website",
    pricingStatus: "freemium",
    subscriptionRequiredForIntendedUse: true,
    automationPermission: "user_interaction_required",
    inputSchema: {
      type: "object",
      properties: {
        category: { type: "string", default: "technology" },
      },
    },
    outputSchema: {
      type: "object",
      properties: {
        renderedMockupUrl: { type: "string" },
      },
    },
    requiredPermissions: ["browser:open_window"],
    supportedPlatforms: ["Browser"],
    availabilityStatus: "RESTRICTED",
    limitations: [
      "Redirected into Canva Mockups ecosystem",
      "Basic standard mockups are free; premium high-resolution templates require Canva Pro",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://www.canva.com/policies/terms-of-use/",
    healthStatus: "DEGRADED",
    riskLevel: "L0",
    actionType: "LAUNCH_EXTERNAL",
  },

  // C. Discovery & Research Tools
  {
    id: "alternative_to",
    name: "AlternativeTo Software Discovery",
    description: "Crowdsourced database for discovering open-source and free alternatives to commercial software.",
    category: "Research & Learning",
    websiteUrl: "https://alternativeto.net/",
    documentationUrl: "https://alternativeto.net/",
    executionMode: "user_opened_website",
    pricingStatus: "free_core",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "approved",
    inputSchema: {
      type: "object",
      properties: {
        softwareName: { type: "string", description: "Target software to replace" },
        licenseFilter: { type: "string", enum: ["opensource", "free", "any"], default: "opensource" },
      },
      required: ["softwareName"],
    },
    outputSchema: {
      type: "object",
      properties: {
        alternatives: { type: "array" },
      },
    },
    requiredPermissions: ["browser:open_window"],
    supportedPlatforms: ["Browser"],
    availabilityStatus: "AVAILABLE",
    limitations: [
      "User-directed search and comparison workflow; respect site rate limits and terms",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://alternativeto.net/about/terms-of-use/",
    healthStatus: "OPERATIONAL",
    riskLevel: "L0",
    actionType: "ALTERNATIVE_SEARCH",
  },
  {
    id: "internet_archive",
    name: "Internet Archive & Wayback Machine",
    description: "Search digital historical archives, public domain media, and historical web snapshot availability.",
    category: "Research & Learning",
    websiteUrl: "https://archive.org/",
    documentationUrl: "https://archive.org/help/wayback_api.php",
    executionMode: "approved_api",
    pricingStatus: "free_core",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "approved",
    inputSchema: {
      type: "object",
      properties: {
        url: { type: "string", description: "Target website URL for Wayback lookup" },
      },
      required: ["url"],
    },
    outputSchema: {
      type: "object",
      properties: {
        available: { type: "boolean" },
        snapshotUrl: { type: "string" },
        timestamp: { type: "string" },
      },
    },
    requiredPermissions: ["external_network:http_get"],
    supportedPlatforms: ["API", "Browser"],
    availabilityStatus: "AVAILABLE",
    limitations: [
      "Public Wayback availability & CDX API only; strictly respects robots.txt and rate limits",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://archive.org/about/terms.php",
    healthStatus: "OPERATIONAL",
    riskLevel: "L0",
    actionType: "WAYBACK_SEARCH",
  },
  {
    id: "project_gutenberg",
    name: "Project Gutenberg Public Domain Library",
    description: "Discover over 70,000 free, eligible public domain books and literary texts via open catalog query.",
    category: "Research & Learning",
    websiteUrl: "https://www.gutenberg.org/",
    documentationUrl: "https://gutendex.com/",
    executionMode: "approved_api",
    pricingStatus: "free_core",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "approved",
    inputSchema: {
      type: "object",
      properties: {
        searchQuery: { type: "string", description: "Title or author to search" },
      },
      required: ["searchQuery"],
    },
    outputSchema: {
      type: "object",
      properties: {
        books: { type: "array" },
      },
    },
    requiredPermissions: ["external_network:http_get"],
    supportedPlatforms: ["API", "Browser"],
    availabilityStatus: "AVAILABLE",
    limitations: [
      "Accesses free Gutendex public domain mirror catalog; does not scrape main gutenberg.org site",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://www.gutenberg.org/policy/permission.html",
    healthStatus: "OPERATIONAL",
    riskLevel: "L0",
    actionType: "GUTENBERG_SEARCH",
  },
  {
    id: "justwatch",
    name: "JustWatch Streaming Guide",
    description: "Discover global movie and TV streaming availability, digital rental platforms, and licensing.",
    category: "Media Discovery",
    websiteUrl: "https://www.justwatch.com/",
    documentationUrl: "https://www.justwatch.com/",
    executionMode: "user_opened_website",
    pricingStatus: "freemium",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "user_interaction_required",
    inputSchema: {
      type: "object",
      properties: {
        title: { type: "string" },
        country: { type: "string", default: "US" },
      },
      required: ["title"],
    },
    outputSchema: {
      type: "object",
      properties: {
        searchUrl: { type: "string" },
      },
    },
    requiredPermissions: ["browser:open_window"],
    supportedPlatforms: ["Browser"],
    availabilityStatus: "AVAILABLE",
    limitations: [
      "Free user search workflow; no free public API; watching streams requires user subscriptions",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://www.justwatch.com/us/terms-of-use",
    healthStatus: "OPERATIONAL",
    riskLevel: "L0",
    actionType: "LAUNCH_EXTERNAL",
  },
  {
    id: "wolfram_alpha",
    name: "WolframAlpha Computational Engine",
    description: "Definitive computational intelligence, symbolic mathematical calculations, chemistry, and physics data.",
    category: "Computational Tools",
    websiteUrl: "https://www.wolframalpha.com/",
    documentationUrl: "https://products.wolframalpha.com/api/",
    executionMode: "user_opened_website",
    pricingStatus: "freemium",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "user_interaction_required",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Mathematical expression or computational inquiry" },
      },
      required: ["query"],
    },
    outputSchema: {
      type: "object",
      properties: {
        resultUrl: { type: "string" },
      },
    },
    requiredPermissions: ["browser:open_window"],
    supportedPlatforms: ["Browser", "API (paid)"],
    availabilityStatus: "AVAILABLE",
    limitations: [
      "Free web interface computation; programmatic Developer API requires Wolfram AppID key",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://www.wolframalpha.com/termsofuse",
    healthStatus: "OPERATIONAL",
    riskLevel: "L0",
    actionType: "LAUNCH_EXTERNAL",
  },
  {
    id: "open_culture",
    name: "Open Culture Educational Commons",
    description: "Curated open educational resources, university courses, audiobooks, and historical archives.",
    category: "Research & Learning",
    websiteUrl: "https://www.openculture.com/",
    documentationUrl: "https://www.openculture.com/",
    executionMode: "user_opened_website",
    pricingStatus: "free_core",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "user_interaction_required",
    inputSchema: {
      type: "object",
      properties: {
        topic: { type: "string" },
      },
    },
    outputSchema: {
      type: "object",
      properties: {
        catalogUrl: { type: "string" },
      },
    },
    requiredPermissions: ["browser:open_window"],
    supportedPlatforms: ["Browser"],
    availabilityStatus: "AVAILABLE",
    limitations: [
      "Open discovery directory; individual linked resources subject to host institutions' policies",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://www.openculture.com/about",
    healthStatus: "OPERATIONAL",
    riskLevel: "L0",
    actionType: "LAUNCH_EXTERNAL",
  },

  // D. Security & Account Safety
  {
    id: "haveibeenpwned",
    name: "Have I Been Pwned Account Safety",
    description: "Cryptographically safe breach and leak verification using k-Anonymity privacy protocols.",
    category: "Security",
    websiteUrl: "https://haveibeenpwned.com/",
    documentationUrl: "https://haveibeenpwned.com/API/v3",
    executionMode: "approved_api",
    pricingStatus: "free_core",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "user_interaction_required",
    inputSchema: {
      type: "object",
      properties: {
        queryType: { type: "string", enum: ["password_pwned_hash_prefix", "web_lookup"] },
        hashPrefix: { type: "string", description: "First 5 chars of SHA-1 hash (k-Anonymity)" },
      },
      required: ["queryType"],
    },
    outputSchema: {
      type: "object",
      properties: {
        pwnedCount: { type: "number" },
        checkedAt: { type: "string" },
      },
    },
    requiredPermissions: ["external_network:http_get", "user:explicit_consent"],
    supportedPlatforms: ["API", "Browser"],
    availabilityStatus: "AVAILABLE",
    limitations: [
      "Requires explicit informed confirmation before external transmission",
      "Uses privacy-preserving k-Anonymity (5-character SHA-1 prefix) for passwords",
      "Zero persistent PII storage in ULTRON system memory",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://haveibeenpwned.com/Privacy",
    healthStatus: "OPERATIONAL",
    riskLevel: "L2",
    actionType: "HIBP_BREACH_CHECK",
  },

  // E. Global Intelligence Workspace Connector
  {
    id: "world_monitor_connector",
    name: "World Monitor Open Intelligence",
    description: "Direct connection to World Monitor open-source intelligence radar, conflict maps, and global telemetry.",
    category: "Global Intelligence",
    websiteUrl: "https://worldmonitor.app/",
    documentationUrl: "https://worldmonitor.app/mcp",
    executionMode: "approved_api",
    pricingStatus: "freemium",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "approved",
    inputSchema: {
      type: "object",
      properties: {
        operation: { type: "string", enum: ["get_sources", "get_status"], default: "get_sources" },
      },
    },
    outputSchema: {
      type: "object",
      properties: {
        sources: { type: "array" },
        providerStatus: { type: "string" },
      },
    },
    requiredPermissions: ["external_network:http_post"],
    supportedPlatforms: ["REST / MCP API", "Browser"],
    availabilityStatus: "AVAILABLE",
    limitations: [
      "get_sources discovery is public, anonymous, and quota-free",
      "Restricted real-time event feeds require WORLDMONITOR_API_KEY environment configuration",
      "Upstream codebase is AGPL-3.0 licensed; accessed strictly over network boundaries",
    ],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://worldmonitor.app/",
    healthStatus: "OPERATIONAL",
    riskLevel: "L0",
    actionType: "WORLD_MONITOR_DISCOVERY",
  },
];

// F. Explicitly Excluded Services Catalog (Section 5.F)
export const EXCLUDED_TOOLS_CATALOG: FreeToolDefinition[] = [
  {
    id: "12ft_io",
    name: "12ft Ladder",
    description: "Third-party paywall bypass proxy.",
    category: "Research & Learning",
    websiteUrl: "https://12ft.io/",
    documentationUrl: "https://12ft.io/",
    executionMode: "user_opened_website",
    pricingStatus: "unverified",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "unverified",
    inputSchema: {},
    outputSchema: {},
    requiredPermissions: [],
    supportedPlatforms: ["Browser"],
    availabilityStatus: "EXCLUDED",
    limitations: ["Automated execution forbidden by ULTRON safety policy"],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://12ft.io/",
    healthStatus: "UNAVAILABLE",
    riskLevel: "L3",
    actionType: "LAUNCH_EXTERNAL",
    excludedReason: "Circumvents access controls and publisher paywalls. Excluded due to anti-circumvention legal liabilities and intermittent service stability.",
  },
  {
    id: "libgen",
    name: "Library Genesis (LibGen)",
    description: "Shadow library hosting unauthorized digitized academic books and papers.",
    category: "Research & Learning",
    websiteUrl: "https://libgen.is/",
    documentationUrl: "https://libgen.is/",
    executionMode: "user_opened_website",
    pricingStatus: "unverified",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "unverified",
    inputSchema: {},
    outputSchema: {},
    requiredPermissions: [],
    supportedPlatforms: ["Browser"],
    availabilityStatus: "EXCLUDED",
    limitations: ["Automated execution forbidden by ULTRON safety policy"],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://libgen.is/",
    healthStatus: "UNAVAILABLE",
    riskLevel: "L3",
    actionType: "LAUNCH_EXTERNAL",
    excludedReason: "Unauthorized distribution of copyrighted materials. Excluded in favor of legitimate open-access repositories (arXiv, Directory of Open Access Books, Project Gutenberg).",
  },
  {
    id: "scihub",
    name: "Sci-Hub",
    description: "Shadow library providing unauthorized access to publisher research databases.",
    category: "Research & Learning",
    websiteUrl: "https://sci-hub.se/",
    documentationUrl: "https://sci-hub.se/",
    executionMode: "user_opened_website",
    pricingStatus: "unverified",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "unverified",
    inputSchema: {},
    outputSchema: {},
    requiredPermissions: [],
    supportedPlatforms: ["Browser"],
    availabilityStatus: "EXCLUDED",
    limitations: ["Automated execution forbidden by ULTRON safety policy"],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://sci-hub.se/",
    healthStatus: "UNAVAILABLE",
    riskLevel: "L3",
    actionType: "LAUNCH_EXTERNAL",
    excludedReason: "Bypasses institutional authentication and publisher licensing. Excluded in favor of lawful preprint repositories, author self-archiving, and open access APIs.",
  },
  {
    id: "pdfdrive",
    name: "PDF Drive",
    description: "Third-party document search engine.",
    category: "Research & Learning",
    websiteUrl: "https://pdfdrive.com/",
    documentationUrl: "https://pdfdrive.com/",
    executionMode: "user_opened_website",
    pricingStatus: "unverified",
    subscriptionRequiredForIntendedUse: false,
    automationPermission: "unverified",
    inputSchema: {},
    outputSchema: {},
    requiredPermissions: [],
    supportedPlatforms: ["Browser"],
    availabilityStatus: "EXCLUDED",
    limitations: ["Automated execution forbidden by ULTRON safety policy"],
    lastVerifiedAt: "2026-10-09T12:00:00Z",
    termsUrl: "https://pdfdrive.com/",
    healthStatus: "UNAVAILABLE",
    riskLevel: "L3",
    actionType: "LAUNCH_EXTERNAL",
    excludedReason: "Unverified copyright status, intrusive advertising scripts, and elevated file download payload security risks. Excluded in favor of verified digital repositories.",
  },
];
